    swagger: "2.0"
    info:
      title: fishtech-api-ip optional-string
      description: "Returns the IP address of that is passed through the url of a cloud function"
      version: "1.0.0"
    schemes:
      - "https"
    paths:
      /:
        get:
          summary: Return an IP address
          operationId: get_ip
          x-google-backend:
            address: https://us-central1-axiomatic-set-305500.cloudfunctions.net/ftg-api-ip-get
          responses:
            '200':
              description: A successful response
              schema:
                type: string